name:          "@mdo'dan Kod Rehberi"
description:   Esnek, uzun ömürlü ve sürdürülebilir HTML ve CSS standartları.
url:           http://hayatbiralem.com/kod-rehberi

markdown:      rdiscount
permalink:     pretty
pygments:      true
